### ISSUE TITLE
config/database.php is missing

### ISSUE THREAD

**Issue by greut** [HE-Arc/cal#12]
Ref. ffe6826d79a6a2a6699b37ed0faf93f03d14e731

**Comment by DoubleSentinel** [comment]
We all have it, its just since we might have different database logins we decided to remove it from the project; If you want us to push the file and add another database config file from which the database.php will get its data -- in which case the config file can be edited.

**Comment by greut** [comment]
Use `.env` for this purpose. Everything is in the documentation:

https://laravel.com/docs/5.3/configuration#environment-configuration

**Comment by DoubleSentinel** [comment]
Still have an issue with this. My main question is, if you look at 
https://github.com/HE-Arc/cal/blob/e81c50c5d688081ea2a856c5b079bf3fecb0b6d6/CalSiteWeb/config/database.php#L59-L61

I don't want these default info to be in clear on git; how do i avoid this whilst still having database.php on the repo? Should i just not put any default value?

**Comment by greut** [comment]
Use `.env` and keep the default values as default as possible.

https://github.com/HE-Arc/webapp-server/blob/master/files/templates/README-php.md#configuring-the-database-connection
