### ISSUE TITLE
Image - Calendar

### ISSUE THREAD

**Issue by DoubleSentinel** [HE-Arc/cal#8]
![calendar](https://cloud.githubusercontent.com/assets/9153038/19929245/c6d80e30-a102-11e6-945d-d13abf7b4b89.png)

**Comment by greut** [comment]
NB: vous n'avez pas besoin de créer l'issue pour obtenir le lien vers l'image.

**Comment by DoubleSentinel** [comment]
Autant pour moi. Merci pour le trick
